export const mockProducts = [
    {
        id: '1',
        name: 'PlayStation 5 Console',
        category: 'consoles',
        brand: 'Sony',
        price: 85000,
        originalPrice: 95000,
        rating: 4.8,
        reviewCount: 128,
        inStock: true,
        storeAvailability: true,
        imageUrl: 'https://picsum.photos/seed/ps5/400/300',
        discount: 15,
        tags: ['Bestseller', 'Exclusive', 'Gaming'],
        features: ['4K Gaming', 'Ray Tracing', 'SSD Storage', 'Backward Compatible'],
        warranty: '2 Years',
        isFeatured: true,
        isFavorite: false,
        stock: 25,
        createdAt: '2024-01-15',
        specs: [
            { name: 'CPU', value: 'AMD Zen 2', icon: 'cpu' },
            { name: 'GPU', value: 'AMD RDNA 2', icon: 'gpu' },
            { name: 'Storage', value: '825GB SSD', icon: 'storage' },
            { name: 'RAM', value: '16GB GDDR6', icon: 'ram' }
        ]
    },
    {
        id: '2',
        name: 'Xbox Series X',
        category: 'consoles',
        brand: 'Microsoft',
        price: 75000,
        originalPrice: 85000,
        rating: 4.7,
        reviewCount: 96,
        inStock: true,
        storeAvailability: true,
        imageUrl: 'https://picsum.photos/seed/xbox/400/300',
        discount: 12,
        tags: ['Bestseller', 'Powerful', 'Gaming'],
        features: ['4K Gaming', '120FPS', 'Quick Resume', 'Game Pass'],
        warranty: '2 Years',
        isFeatured: true,
        isFavorite: false,
        stock: 18,
        createdAt: '2024-01-10'
    },
    {
        id: '3',
        name: 'Gaming PC RTX 4070',
        category: 'pc-gaming',
        brand: 'NVIDIA',
        price: 250000,
        originalPrice: 280000,
        rating: 4.9,
        reviewCount: 45,
        inStock: true,
        storeAvailability: true,
        imageUrl: 'https://picsum.photos/seed/pc/400/300',
        discount: 11,
        tags: ['High-End', 'RTX', 'Gaming'],
        features: ['RTX 4070', '32GB RAM', '2TB SSD', 'RGB Lighting'],
        warranty: '3 Years',
        isFeatured: true,
        isFavorite: false,
        stock: 8,
        createdAt: '2024-02-01'
    },
    {
        id: '4',
        name: 'Gaming Headset RGB',
        category: 'peripherals',
        brand: 'Razer',
        price: 12000,
        originalPrice: 15000,
        rating: 4.5,
        reviewCount: 234,
        inStock: true,
        storeAvailability: true,
        imageUrl: 'https://picsum.photos/seed/headset/400/300',
        discount: 20,
        tags: ['Wireless', '7.1 Surround', 'RGB'],
        features: ['Wireless', 'Noise Cancelling', 'RGB Lights', '7.1 Surround'],
        warranty: '1 Year',
        isFeatured: false,
        isFavorite: false,
        stock: 50,
        createdAt: '2024-01-20'
    },
    {
        id: '5',
        name: 'Mechanical Keyboard',
        category: 'peripherals',
        brand: 'Logitech',
        price: 8000,
        originalPrice: 10000,
        rating: 4.3,
        reviewCount: 189,
        inStock: true,
        storeAvailability: true,
        imageUrl: 'https://picsum.photos/seed/keyboard/400/300',
        discount: 20,
        tags: ['Mechanical', 'RGB', 'Gaming'],
        features: ['Mechanical Switches', 'RGB Backlight', 'Media Controls'],
        warranty: '1 Year',
        isFeatured: false,
        isFavorite: false,
        stock: 35,
        createdAt: '2024-01-25'
    },
    {
        id: '6',
        name: 'Gaming Chair Pro',
        category: 'accessories',
        brand: 'DXRacer',
        price: 45000,
        originalPrice: 55000,
        rating: 4.6,
        reviewCount: 89,
        inStock: true,
        storeAvailability: true,
        imageUrl: 'https://picsum.photos/seed/chair/400/300',
        discount: 18,
        tags: ['Ergonomic', 'Comfort', 'Gaming'],
        features: ['Ergonomic Design', 'Adjustable Height', 'Lumbar Support'],
        warranty: '2 Years',
        isFeatured: true,
        isFavorite: false,
        stock: 12,
        createdAt: '2024-02-05'
    }
];