// inventory.data.js
export const stores = [
    { id: 'store-1', name: 'Nairobi Main Store', code: 'NBO-001', status: 'active' },
    { id: 'store-2', name: 'Mombasa Branch', code: 'MBA-002', status: 'active' },
    { id: 'store-3', name: 'Kisumu Outlet', code: 'KSM-003', status: 'maintenance' },
    { id: 'store-4', name: 'Eldoret Branch', code: 'ELD-004', status: 'active' },
    { id: 'store-5', name: 'Nakuru Store', code: 'NAK-005', status: 'inactive' },
];

export const categories = [
    { id: 'all', name: 'All Categories', count: 156, icon: 'Layers' },
    { id: 'gaming-pcs', name: 'Gaming PCs', count: 24, icon: 'Cpu' },
    { id: 'gaming-laptops', name: 'Gaming Laptops', count: 18, icon: 'Laptop' },
    { id: 'consoles', name: 'Consoles', count: 12, icon: 'Gamepad' },
    { id: 'gaming-monitors', name: 'Gaming Monitors', count: 15, icon: 'Monitor' },
    { id: 'gaming-headsets', name: 'Gaming Headsets', count: 28, icon: 'Headphones' },
    { id: 'mechanical-keyboards', name: 'Mechanical Keyboards', count: 32, icon: 'Keyboard' },
    { id: 'gaming-mice', name: 'Gaming Mice', count: 45, icon: 'Mouse' },
    { id: 'electrical', name: 'Electrical', count: 42, icon: 'Zap' },
    { id: 'accessories', name: 'Accessories', count: 60, icon: 'Package' },
];

export const inventoryStats = {
    totalItems: 156,
    totalValue: 2850000,
    lowStockItems: 12,
    outOfStock: 4,
    averageStock: 45,
    turnoverRate: 2.4,
    lastUpdated: '2024-03-15',
    monthlyGrowth: 12.5,
    weeklySales: 42,
};



export const inventoryItems = [
    {
        id: 1,
        name: 'Gaming PC Pro',
        sku: 'GAM-789456',
        category: 'gaming-pcs',
        currentStock: 8,
        minStock: 10,
        status: 'Low Stock',
        storeStock: { 'store-1': 5, 'store-2': 3, 'store-3': 0 },
        value: 120000,
        lastMovement: '2024-03-14',
        brand: 'Alienware',
        color: 'Lunar Light',
        lastSold: '2024-03-14',
        totalSold: 45,
    },
    {
        id: 2,
        name: 'Mechanical Keyboard',
        sku: 'ACC-123456',
        category: 'accessories',
        currentStock: 25,
        minStock: 15,
        status: 'In Stock',
        storeStock: { 'store-1': 10, 'store-2': 8, 'store-3': 7 },
        value: 45000,
        lastMovement: '2024-03-15',
        brand: 'Razer',
        color: 'Black',
        lastSold: '2024-03-15',
        totalSold: 120,
    },
    {
        id: 3,
        name: '4K Gaming Monitor',
        sku: 'MON-456789',
        category: 'gaming-monitors',
        currentStock: 0,
        minStock: 5,
        status: 'Out of Stock',
        storeStock: { 'store-1': 0, 'store-2': 0, 'store-3': 0 },
        value: 0,
        lastMovement: '2024-03-10',
        brand: 'ASUS',
        color: 'Black',
        lastSold: '2024-03-09',
        totalSold: 28,
    },
    {
        id: 4,
        name: 'Electrical Switch Panel',
        sku: 'ELC-987654',
        category: 'electrical',
        currentStock: 42,
        minStock: 20,
        status: 'In Stock',
        storeStock: { 'store-1': 15, 'store-2': 15, 'store-3': 12 },
        value: 84000,
        lastMovement: '2024-03-13',
        brand: 'Schneider',
        color: 'White',
        lastSold: '2024-03-13',
        totalSold: 65,
    },
    {
        id: 5,
        name: 'PS5 Console',
        sku: 'CON-321654',
        category: 'consoles',
        currentStock: 6,
        minStock: 8,
        status: 'Low Stock',
        storeStock: { 'store-1': 4, 'store-2': 2, 'store-3': 0 },
        value: 300000,
        lastMovement: '2024-03-14',
        brand: 'Sony',
        color: 'White',
        lastSold: '2024-03-14',
        totalSold: 89,
    },
    {
        id: 6,
        name: 'Gaming Chair Pro',
        sku: 'CHA-159753',
        category: 'gaming-chairs',
        currentStock: 18,
        minStock: 10,
        status: 'In Stock',
        storeStock: { 'store-1': 8, 'store-2': 6, 'store-3': 4 },
        value: 216000,
        lastMovement: '2024-03-12',
        brand: 'Secretlab',
        color: 'Stealth',
        lastSold: '2024-03-12',
        totalSold: 34,
    },
];

export const tabs = [
    { id: 'overview', name: 'Overview', icon: 'Home' },
    { id: 'all-items', name: 'All Items', icon: 'Package' },
    { id: 'low-stock', name: 'Low Stock', icon: 'AlertTriangle' },
    { id: 'out-of-stock', name: 'Out of Stock', icon: 'AlertTriangle' },
    { id: 'movement', name: 'Movement', icon: 'TrendingUp' },
    { id: 'analytics', name: 'Analytics', icon: 'BarChart3' },
    { id: 'transfers', name: 'Transfers', icon: 'RefreshCw' },
];

export const statusColors = {
    'In Stock': 'bg-green-500/10 text-green-400 border border-green-500/20',
    'Low Stock': 'bg-yellow-500/10 text-yellow-400 border border-yellow-500/20',
    'Out of Stock': 'bg-red-500/10 text-red-400 border border-red-500/20',
    'active': 'bg-green-500/10 text-green-400 border border-green-500/20',
    'inactive': 'bg-gray-500/10 text-gray-400 border border-gray-500/20',
    'maintenance': 'bg-blue-500/10 text-blue-400 border border-blue-500/20',
};

export const inventoryActions = [
    { id: 'transfer', name: 'Transfer Stock', icon: 'RefreshCw', description: 'Move items between stores' },
    { id: 'adjust', name: 'Adjust Stock', icon: 'Edit', description: 'Manual stock adjustment' },
    { id: 'restock', name: 'Restock', icon: 'Package', description: 'Order new inventory' },
    { id: 'export', name: 'Export Data', icon: 'Download', description: 'Download inventory reports' },
    { id: 'import', name: 'Import Data', icon: 'Upload', description: 'Bulk update inventory' },
    { id: 'audit', name: 'Start Audit', icon: 'ClipboardCheck', description: 'Physical inventory count' },
];